### PR TITLE
Added validations for models

### PR DESCRIPTION
**Pull request by Nobaltha**

### CODE REVIEW

**Comment by oscargay** [comment]
@Nobaltha - Looks good - I'm not sure how validations work with devise. I think first_name and last_name look good but I think devise automatically validates email and password behind the scenes - not entirely sure though...

**Comment by AnthonyHad** [comment]
Agreed @oscargay I think devise handles the regex for email and password characters other than this I think it's okay

**Comment by Nobaltha** [comment]
@oscargay indeed the uniqueness of email and password is handled by devise

**Comment by Nobaltha** [comment]
@oscargay @AnthonyHad I just wanted to add the basic validations, we can add more later if needed

**Pull request merged**
